import { NodeType } from "../../components/FileSystemView/common";
import { RootDirectoryStructure } from "../../components/FileSystemView/directory";
import profilePicture from "../../../public/person.jpeg";

export const ABOUT_FSV_DATA: RootDirectoryStructure = [
    {
        name: "home",
        type: NodeType.DIR,
        children: [
            {
                name: "robigan",
                type: NodeType.DIR,
                children: [
                    {
                        name: "Documents",
                        type: NodeType.DIR,
                        children: [
                            {
                                name: "whoami.txt",
                                type: NodeType.FILE,
                                contents: <>
                                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium consequatur reiciendis aut nisi perferendis aliquam architecto. Itaque placeat voluptatum dignissimos sapiente odio eius inventore distinctio esse magnam voluptatibus, nam laboriosam.</p>
                                </>
                            },
                        ],
                    },
                    {
                        name: "Downloads",
                        type: NodeType.DIR,
                        children: [
                            {
                                name: "profile-picture.jpg",
                                type: NodeType.IMAGE,
                                contents: profilePicture
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        name: "etc",
        type: NodeType.DIR,
        children: [
            {
                name: "locale.gen",
                type: NodeType.FILE,
                contents: <>
                    <p># Configuration file for locale-gen</p>
                    <p># This file describes all the languages to be added to the host</p>
                    <p>#</p>
                    <p># Lists of locales that are to be generated by the locale-gen command</p>
                    <p>en_US.UTF-8</p>
                    <p>it_IT.UTF-8</p>
                    <p>fr_FR.UTF-8</p>
                </>
            }
        ]
    },
    {
        name: "dev",
        type: NodeType.DIR,
        children: [
            {
                name: "gps",
                type: NodeType.FILE,
                contents: "italy"
            }
        ]
    }
];