# Workflow to test CI for dev branches
name: CI

on:
  push:
    branches: [ development, main ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'README.md'
  pull_request:
    branches: [ development, main ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  next:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm install
        
      - name: Lint test
        run: npm run lint

      - name: Build test
        run: npm run build
        
  dependencies:
    needs: next
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Check up-to date dependencies
        id: check-deps
        run: npm run check-deps
        continue-on-error: true

      - name: Report non up-to date dependencies
        if: ${{ steps.check-deps.conclusion == "success" }}
        run: npm run available-ups